//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoOrderRegister.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KoOrderRegister.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ügyfél hozzáadása/változtatása.
        /// </summary>
        public static string AddOrChangeCostumer {
            get {
                return ResourceManager.GetString("AddOrChangeCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím.
        /// </summary>
        public static string AddresHeader {
            get {
                return ResourceManager.GetString("AddresHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím:.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Biztosan törölni szeretnéd a/az.
        /// </summary>
        public static string AreYouSureWantDeleteCostumer_1 {
            get {
                return ResourceManager.GetString("AreYouSureWantDeleteCostumer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ügyfél adatait?.
        /// </summary>
        public static string AreYouSureWantDeleteCostumer_2 {
            get {
                return ResourceManager.GetString("AreYouSureWantDeleteCostumer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string CancleHeader {
            get {
                return ResourceManager.GetString("CancleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítás.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatbázis ellenőrzése.
        /// </summary>
        public static string CheckDatabase {
            get {
                return ResourceManager.GetString("CheckDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés megerősítése.
        /// </summary>
        public static string ConformationDelete {
            get {
                return ResourceManager.GetString("ConformationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapcsolat.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (Twitter) kapcsolat.
        /// </summary>
        public static string ContactX {
            get {
                return ResourceManager.GetString("ContactX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatbázis elérési útvonala:.
        /// </summary>
        public static string DatabaseLocationLabel {
            get {
                return ResourceManager.GetString("DatabaseLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatbázis elérési útvonala.
        /// </summary>
        public static string DatabaseLocationSelect {
            get {
                return ResourceManager.GetString("DatabaseLocationSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ügyfél adatainak törlése (a rendelései megmaradnak).
        /// </summary>
        public static string DeleteCostumerTitle {
            get {
                return ResourceManager.GetString("DeleteCostumerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string DeleteHeader {
            get {
                return ResourceManager.GetString("DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelés törlése.
        /// </summary>
        public static string DeleteOrderTitle {
            get {
                return ResourceManager.GetString("DeleteOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés törlése.
        /// </summary>
        public static string DeleteSearchesTitle {
            get {
                return ResourceManager.GetString("DeleteSearchesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejlesztő.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejlesztő weboldala.
        /// </summary>
        public static string DeveloperWebPage {
            get {
                return ResourceManager.GetString("DeveloperWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem sikerült adatbázist létrehozni..
        /// </summary>
        public static string ErrorDataaseConnection {
            get {
                return ResourceManager.GetString("ErrorDataaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem sikerült törölni az ügyél adatait, mert a kiválasztott elem nem a várt típusú..
        /// </summary>
        public static string ErrorDeleteCostumer {
            get {
                return ResourceManager.GetString("ErrorDeleteCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl törlésénél!.
        /// </summary>
        public static string ErrorFileDelete {
            get {
                return ResourceManager.GetString("ErrorFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl átnevezése során..
        /// </summary>
        public static string ErrorFileRename {
            get {
                return ResourceManager.GetString("ErrorFileRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibaüzenet:.
        /// </summary>
        public static string ErrorMsgLabel {
            get {
                return ResourceManager.GetString("ErrorMsgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a rendelés törlése során!.
        /// </summary>
        public static string ErrorOrderDelete {
            get {
                return ResourceManager.GetString("ErrorOrderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a ügyfél mentése során!.
        /// </summary>
        public static string ErrorSavingCostumer {
            get {
                return ResourceManager.GetString("ErrorSavingCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az adatok mentése során!.
        /// </summary>
        public static string ErrorSavingData {
            get {
                return ResourceManager.GetString("ErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl mentésénél!.
        /// </summary>
        public static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem sikerült adatbázist létrehozni.
        /// </summary>
        public static string FaliedDatabaseConnection {
            get {
                return ResourceManager.GetString("FaliedDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAJ szám.
        /// </summary>
        public static string InsuranceNumberHeader {
            get {
                return ResourceManager.GetString("InsuranceNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAJ szám:.
        /// </summary>
        public static string InsuranceNumberLabel {
            get {
                return ResourceManager.GetString("InsuranceNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem megfelelő az adatbázis, készíts egy újat vagy válasz egy másikat..
        /// </summary>
        public static string InValidDatabes {
            get {
                return ResourceManager.GetString("InValidDatabes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új adatbázis létrehozása.
        /// </summary>
        public static string NewDataBase {
            get {
                return ResourceManager.GetString("NewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új ügyfél.
        /// </summary>
        public static string NewMan {
            get {
                return ResourceManager.GetString("NewMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új Rendelés hozzáadása.
        /// </summary>
        public static string NewOrederTitle {
            get {
                return ResourceManager.GetString("NewOrederTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejegyzés:.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott fájl nem található..
        /// </summary>
        public static string NotFoundFile {
            get {
                return ResourceManager.GetString("NotFoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megnyitás.
        /// </summary>
        public static string OpenHeader {
            get {
                return ResourceManager.GetString("OpenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelés kiadásának dátuma:.
        /// </summary>
        public static string OrderCompletionDateLabel {
            get {
                return ResourceManager.GetString("OrderCompletionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelés dátuma:.
        /// </summary>
        public static string OrderDateLabel {
            get {
                return ResourceManager.GetString("OrderDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelési szám:.
        /// </summary>
        public static string OrderNumberLable {
            get {
                return ResourceManager.GetString("OrderNumberLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendelés nyilvántartó.
        /// </summary>
        public static string OrderRegisterTitle {
            get {
                return ResourceManager.GetString("OrderRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fénykép kiválasztása:.
        /// </summary>
        public static string PictureChoiceLabel {
            get {
                return ResourceManager.GetString("PictureChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kép.
        /// </summary>
        public static string PictureHeader {
            get {
                return ResourceManager.GetString("PictureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átnevezés.
        /// </summary>
        public static string RenameHeader {
            get {
                return ResourceManager.GetString("RenameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmentett ügyfelek:.
        /// </summary>
        public static string SavedCostomersLabel {
            get {
                return ResourceManager.GetString("SavedCostomersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string SaveHeader {
            get {
                return ResourceManager.GetString("SaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eszközre mentés.
        /// </summary>
        public static string SaveInDeviceHeader {
            get {
                return ResourceManager.GetString("SaveInDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forráskód (GitHub).
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        public static string SourceTitle {
            get {
                return ResourceManager.GetString("SourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok sikeresen elmentve!.
        /// </summary>
        public static string SuccessfullSaving {
            get {
                return ResourceManager.GetString("SuccessfullSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok sikeresen frissitve!.
        /// </summary>
        public static string SuccessfullUpdating {
            get {
                return ResourceManager.GetString("SuccessfullUpdating", resourceCulture);
            }
        }
    }
}
