name: Publish_DEV

env:
  branch-name: 'develop'
  varrible: 'DEV_VERSION'

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.version.outputs.newVersion }}
      versionCode: ${{ steps.version.outputs.versionCode }}
      minorVersion: ${{ steps.version.outputs.minorVersion }}
    steps:
      # 1) Globális safe.directory beállítás a Git számára, hogy ne panaszkodjon tulajdonjogra.
      - name: Configure Git safe directory (Ubuntu)
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # 2) Checkout a repóba (nem törlünk semmit kézzel, a manual init miatt amúgy is felülírjuk).
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          # Fontos: clean: false => ne töröljön automatikusan, mielőtt klónoz!
          clean: false

      # 3) Manually initialize Git repository (ha mindenképp kell a fetch + reset).
      - name: Manually initialize Git repository
        run: |
          git init
          git remote remove origin || true
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin refs/heads/develop
          git reset --hard FETCH_HEAD

      # Itt helyezheted el a verziószám kiszámítását / beállítását is:
      # - name: Calculate version
      #   id: version
      #   run: ...
      #
      # outputs:
      #   newVersion: ${{ steps.version.outputs.newVersion }}
      #   versionCode: ${{ steps.version.outputs.versionCode }}
      #   minorVersion: ${{ steps.version.outputs.minorVersion }}

  build-apk:
    runs-on: windows-latest
    needs: prepare-version
    steps:
      # 1) Opcionális: saját kézi törlés, ha maradt valami a workspace-ben
      - name: Cleanup runner workspace
        run: |
          if exist D:\git_runner\actions-runner\_work\KoOrderRegister\KoOrderRegister (
            rd /s /q D:\git_runner\actions-runner\_work\KoOrderRegister\KoOrderRegister
          ) else (
            echo "Directory not found"
          )
        shell: cmd

      # 2) Globális safe.directory beállítás, mielőtt a Checkout Action futna.
      - name: Configure Git safe directory (Windows)
        run: |
          git config --global --add safe.directory "D:/git_runner/actions-runner/_work/KoOrderRegister/KoOrderRegister"
        shell: cmd

      # 3) Checkout (fetch-depth=0, clean: false – ne törölje a repót újra).
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          clean: false

      - name: Debug Output Values
        run: |
          echo New Version: ${{ needs.prepare-version.outputs.newVersion }}
          echo Version Code: ${{ needs.prepare-version.outputs.versionCode }}
        shell: cmd

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET MAUI Android workloads
        run: dotnet workload install maui-android
        shell: cmd

      - name: Install .NET SDK maui
        run: dotnet workload install maui
        shell: cmd

      - name: Run APK build script
        run: .\build_apk.bat
        shell: cmd
        env:
          KEYPASS: ${{ secrets.KEYPASS }}
          NEW_VERSION: ${{ needs.prepare-version.outputs.newVersion }}
          NEW_VERSION_CODE: ${{ needs.prepare-version.outputs.versionCode }}
          BUILD_VERSION: ${{ env.varrible }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: output\*.apk

  release:
    runs-on: [self-hosted, Windows]
    needs: [prepare-version, build-apk]
    steps:
      # 1) Opcionális: töröljük a workspace-et
      - name: Cleanup runner workspace
        run: |
          if exist D:\git_runner\actions-runner\_work\KoOrderRegister\KoOrderRegister (
            rd /s /q D:\git_runner\actions-runner\_work\KoOrderRegister\KoOrderRegister
          ) else (
            echo "Directory not found"
          )
        shell: cmd

      # 2) Biztonságos könyvtár hozzáadása a git globális confighoz
      - name: Configure Git safe directory (Self-hosted Windows)
        run: |
          git config --global --add safe.directory "D:/git_runner/actions-runner/_work/KoOrderRegister/KoOrderRegister"
        shell: cmd

      # 3) Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          clean: false

      # 4) Letöltjük az előző job-ban feltöltött APK-t
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-artifact

      - name: Move APK Artifact
        run: move *.apk output\
        shell: cmd

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.apk
          tag_name: ${{ needs.prepare-version.outputs.versionCode }}.${{ needs.prepare-version.outputs.minorVersion }}
          release_name: ${{ needs.prepare-version.outputs.newVersion }}
          body_path: Technical/release_base.md
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
