name: Publish

env:
  branch-name: 'main'

on:
  pull_request:
    branches:
      - main


jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.version.outputs.new-version }}
      versionCode: ${{ steps.version.outputs.versionCode }}
      minor-version: ${{ steps.version.outputs.minor-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Show version.txt content
        run: cat version.txt
      - name: Read Version
        id: version
        run: |
          awk -F'.' '{print $1 "." ($2 + 1) "." $3}' version.txt > temp_version.txt && mv temp_version.txt version.txt
          MAJOR=$(awk -F'.' '{print $1}' version.txt)
          MINOR=$(awk -F'.' '{print $2}' version.txt)
          PATCH=$(awk -F'.' '{print $3}' version.txt)
          VERSION_CODE=$MAJOR
          echo "::set-output name=new-version::$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=versionCode::$VERSION_CODE"
          echo "::set-output name=minor-version::$MINOR"
          echo "Current version: $MAJOR.$MINOR.$PATCH"
          echo "Version Code: $VERSION_CODE"
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and switch to new branch
        run: |
          git checkout -b version-update/$MAJOR-$MINOR-$PATCH


      - name: Commit changes
        run: |
          git add version.txt
          git commit -m "Update version to $MAJOR-$MINOR-$PATCH"

      - name: Push new branch to repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-update/$MAJOR.$MINOR.$PATCH

      - name: Merge branch into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Merge the new branch into main
          git checkout main
          git pull origin main
          git merge --no-ff version-update/$MAJOR.$MINOR.$PATCH -m "Merge version-update/$MAJOR.$MINOR.$PATCH into main"
          # Push the updated main branch
          git push origin main

      - name: Delete the new branch locally and remotely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete the branch locally
          git branch -D version-update/$MAJOR.$MINOR.$PATCH
          # Delete the branch remotely
          git push origin --delete version-update/$MAJOR.$MINOR.$PATCH

  build:
    runs-on: [self-hosted, Windows]
    needs: prepare-version
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Debug Output Values
        run: |
          echo "New Version: ${{ needs.prepare-version.outputs.new-version }}"
          echo "Version Code: ${{ needs.prepare-version.outputs.versionCode }}"
      - name: Install Certificate with Admin Privileges
        run: |
          Start-Process powershell -ArgumentList "Import-PfxCertificate -FilePath KoOrderRegister\Technical\kor.pfx -CertStoreLocation Cert:\LocalMachine\My -Password (ConvertTo-SecureString -String kor -Force -AsPlainText)" -Verb RunAs
        shell: powershell
      - name: Install .NET MAUI Android workloads
        run: dotnet workload install maui-android
      - name: Install .NET SDK maui
        run: dotnet workload install maui
      - name: Run build script
        run: cmd /c ".\build.bat"
        env:
          KEYPASS: ${{ secrets.KEYPASS }}
          NEW_VERSION: ${{ needs.prepare-version.outputs.new-version }}
          NEW_VERSION_CODE: ${{ needs.prepare-version.outputs.versionCode }}
      - name: Install GitHub CLI
        run: |
          $cliUri = "https://github.com/cli/cli/releases/download/v2.57.0/gh_2.57.0_windows_amd64.msi"
          $cliPath = "$env:TEMP\gh_2.57.0_windows_amd64.msi"
          Invoke-WebRequest -Uri $cliUri -OutFile $cliPath
          Start-Process msiexec.exe -Wait -ArgumentList "/i $cliPath /quiet"
          $ghPath = "C:\Program Files\GitHub CLI"
          Write-Output "PATH=$ghPath;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.apk,output/*.msix
          tag_name: ${{ needs.prepare-version.outputs.versionCode }}.${{ needs.prepare-version.outputs.minor-version }}
          release_name: ${{ needs.prepare-version.outputs.new-version }}
          body_path: Technical/release_base.md
          draft: true
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
