name: Windows-test

env:
  branch-name: '92-create-github-runner'  

on:
  push:
    branches: 
      - 92-create-github-runner  
  pull_request:
    branches: 
      - 92-create-github-runner 

jobs:      
 build-android:
    runs-on: [self-hosted, Windows]
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  
    - name: Install Certificate
       run: |
         $CertPassword = ConvertTo-SecureString -String kor -Force -AsPlainText
         Import-PfxCertificate -FilePath KoOrderRegister\Technical\kor.pfx -CertStoreLocation Cert:\LocalMachine\My -Password $CertPassword
  shell: powershell
    - name: Install .NET MAUI workloads
      run: dotnet workload install maui-android
    - name: Run build script
      run: cmd /c ".\build.bat"
      env:
        KEYPASS: ${{ secrets.KEYPASS }}